"""add unique constraint on stores.owner_id

Revision ID: b56ec15594ae
Revises: 376675eb93f2
Create Date: 2026-06-15 18:10:22.828924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56ec15594ae'
down_revision: Union[str, Sequence[str], None] = '376675eb93f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stores', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    # ### end Alembic commands ###
